name=PxGraph_ST7781_Shield
version=1.0.0
author=Olivier Pécheux
maintainer=Olivier <Olivier@Dansetrad.fr>
sentence=Allows Arduino boards to control a screen shield with a ST7781. For Arduino UNO. For Arduino MEGA.
paragraph=Cette bibliotèque permet de gérer un écran graphique enfichable sur Uno si il est équipé d'un driver ST7781.
category=Device Control
url=http://arduino.dansetrad.fr/Px_Graph 
architectures=avr
includes=PxGraph_ST7781_Shield.h